# Generated by Django 3.2.2 on 2021-05-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0003_alter_contact_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='addresses',
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app_contact.contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('RES', 'private'), ('SME', 'business')], default='RES', max_length=3),
        ),
    ]
